# Generated by Django 5.2.6 on 2026-01-25 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('import', '导入'), ('modify', '修改'), ('delete', '删除')], max_length=10, unique=True, verbose_name='模板类型')),
                ('column_definitions', models.TextField(verbose_name='列定义(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模板配置',
                'verbose_name_plural': '模板配置',
            },
        ),
        migrations.CreateModel(
            name='ColumnOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100, verbose_name='列名')),
                ('option_value', models.CharField(max_length=200, verbose_name='可选项值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '列可选值',
                'verbose_name_plural': '列可选值清单',
                'indexes': [models.Index(fields=['column_name'], name='ucm_app_col_column__815ddb_idx')],
                'unique_together': {('column_name', 'option_value')},
            },
        ),
        migrations.CreateModel(
            name='ManufacturerVersionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100, verbose_name='设备类型')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='厂商')),
                ('version', models.CharField(max_length=100, verbose_name='版本')),
                ('auth_method', models.CharField(max_length=100, verbose_name='认证方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '厂商版本信息',
                'verbose_name_plural': '厂商版本信息',
                'indexes': [models.Index(fields=['device_type', 'manufacturer', 'version'], name='ucm_app_man_device__eb4e00_idx')],
                'unique_together': {('device_type', 'manufacturer', 'version', 'auth_method')},
            },
        ),
        migrations.CreateModel(
            name='UCMDeviceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('device_type', models.CharField(max_length=100, verbose_name='设备类型')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='厂商')),
                ('version', models.CharField(max_length=100, verbose_name='版本')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('other_ips', models.TextField(blank=True, null=True, verbose_name='其他IP')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='安装位置')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='分组')),
                ('auth_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='认证方式')),
                ('import_time', models.DateTimeField(verbose_name='导入时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'UCM设备清单',
                'verbose_name_plural': 'UCM设备清单',
                'indexes': [models.Index(fields=['name'], name='ucm_app_ucm_name_981c58_idx'), models.Index(fields=['ip'], name='ucm_app_ucm_ip_8ec70d_idx'), models.Index(fields=['device_type'], name='ucm_app_ucm_device__88c1f6_idx'), models.Index(fields=['manufacturer'], name='ucm_app_ucm_manufac_8beb87_idx')],
                'unique_together': {('name', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='UCMRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('import', '导入'), ('modify', '修改'), ('delete', '删除')], max_length=10, verbose_name='需求类型')),
                ('ucm_change_date', models.DateField(verbose_name='UCM变更日期')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理')], default='pending', max_length=10, verbose_name='状态')),
                ('process_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('requirement_data', models.TextField(verbose_name='需求数据(JSON)')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requirements', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': 'UCM需求登记',
                'verbose_name_plural': 'UCM需求登记',
                'indexes': [models.Index(fields=['ucm_change_date'], name='ucm_app_ucm_ucm_cha_919438_idx'), models.Index(fields=['submitter'], name='ucm_app_ucm_submitt_7c7d2a_idx'), models.Index(fields=['status'], name='ucm_app_ucm_status_a81df0_idx'), models.Index(fields=['name'], name='ucm_app_ucm_name_25d939_idx'), models.Index(fields=['ip'], name='ucm_app_ucm_ip_566b18_idx'), models.Index(fields=['requirement_type'], name='ucm_app_ucm_require_d997c5_idx')],
            },
        ),
    ]
