# Generated by Django 5.2.10 on 2026-01-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucm_app', '0002_ucmdateconfig'),
    ]

    operations = [
    ]
